# from https://github.com/r-lib/actions/tree/master/examples
on: [push]
#  push:
#    paths:
#      - README.Rmd

name: Render README

jobs:
  render:
    name: Render README
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: is brew installed?
        run: brew -v
      #- name: install brew
      #  run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
      #- name: install gdal
      #  run: |
      #    brew install pkg-config 
      #    brew install gdal
      - name: Install rmarkdown + other packages
        run: Rscript -e "install.packages(c('sf', 'rmarkdown', 'jsonlite', 'magrittr', 'ggplot2', 'xml2', 'osmdata', 'readxl'))"
      - name: Render README
        run: Rscript -e 'rmarkdown::render("README.Rmd")'
      - name: Commit results
        run: |
          git commit README.md -m 'Re-build README.Rmd' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
